name: yodravet
description: Una app de A.E Yo corro por el Dravet.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 3.0.3+41
#version: 3.0.0

environment:
  #  sdk: ">=2.16.0-80.1.beta <3.0.0"
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_cupertino_localizations
  # flutter_cupertino_localizations: ^1.0.1
  # https://pub.dev/packages/intl_translation
  # intl_translation: ^0.17.10+1
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.4.0
  # https://pub.dartlang.org/packages/bloc
  bloc: ^8.1.1
  # https://pub.dartlang.org/packages/flutter_bloc
  flutter_bloc: ^8.1.2
  # https://pub.dev/packages/google_fonts
  google_fonts: ^4.0.4
  # https://pub.dev/packages/responsive_builder
  responsive_builder: ^0.6.4
  # https://pub.dev/packages/strava_flutter
  #  strava_flutter: ^1.2.2+62
#  strava_flutter:
#    git: https://github.com/dreampowder/strava_flutter.git
#    git: https://github.com/pedrocortizo/strava_flutter
  # https://pub.dev/packages/strava_client
  strava_client: ^2.1.0
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^4.7.0
  # cloud_firestore: ^1.0.7
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^4.6.0
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^6.1.0
  # https://pub.dev/packages/google_sign_in_web
  # google_sign_in_web: ^0.9.2
  # https://pub.dartlang.org/packages/firebase_analytics
  # firebase_analytics: ^7.0.1
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.12.0
  # https://pub.dev/packages/rive
  rive: ^0.10.4
  # https://pub.dev/packages/countup
  #  countup: ^0.1.3
  countup:
    git: https://github.com/alpceylan/flutter-countup.git
  # https://pub.dev/packages/number_inc_dec
  number_inc_dec: ^0.8.0
  # https://pub.dev/packages/flash
  flash: ^3.0.3+5
  # https://pub.dev/packages/email_validator
  email_validator: ^2.1.17
  # https://pub.dev/packages/sign_in_with_apple
  # https://firebase.flutter.dev/docs/auth/social/
  sign_in_with_apple: ^4.3.0
  # https://pub.dev/packages/crypto
  crypto: ^3.0.3
  # https://pub.dev/packages/animations
  animations: ^2.0.7
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.11
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.0
  # https://pub.dev/packages/assets_audio_player
  assets_audio_player: 3.0.6
  # https://pub.dev/packages/share_plus
  share_plus: ^6.3.4
  # https://pub.dev/packages/cached_network_image_builder
  #  cached_network_image_builder: ^0.2.0
  # https://pub.dev/packages/firebase_image
  #  firebase_image: ^1.1.1
  # https://pub.dev/packages/image_cacheing
  #  image_cacheing: ^0.0.2
  # https://pub.dev/packages/image_network
  #  image_network: ^2.5.1
  # https://pub.dev/packages/extended_image
  #  extended_image: ^6.2.0
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  # https://pub.dev/packages/intro_slider
  intro_slider: ^4.2.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.1.1
  # https://pub.dev/packages/animated_bottom_navigation_bar
  animated_bottom_navigation_bar: ^1.2.0
  # https://pub.dev/packages/badges
  badges: ^3.1.1
  # https://pub.dev/packages/any_link_preview
  any_link_preview: ^3.0.0
  # https://pub.dev/packages/bubble
  bubble: ^1.2.1
  # https://pub.dev/packages/flutter_side_menu
  flutter_side_menu: ^0.3.2
  # https://pub.dev/packages/flutter_cors
  flutter_cors: ^1.3.2
  # https://pub.dev/packages/flutter_app_version_checker
#  flutter_app_version_checker: ^0.3.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # https://pub.dev/packages/flutter_launcher_name
  #  flutter_launcher_name: ^0.0.1
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"
# run flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.webp"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/icon/icon.png"
# run flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "Yo Dravet"
flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/
    - assets/images/stores/
    - assets/images/race/
    - assets/images/medallas/
    - assets/images/race/stages/
    - assets/images/race/stages/researchers/
    - assets/music/
    - lib/
    - lib/src/
    - lib/src/dao/
    - lib/src/dao/interface/
    - lib/src/bloc/
    - lib/src/bloc/event/
    - lib/src/bloc/state/
    - lib/src/bloc/interface/
    - lib/src/page/
    - lib/src/page/feed/
    - lib/src/page/home/
    - lib/src/page/home/widget/
    - lib/src/page/race/
    - lib/src/page/race/widget/
    - lib/src/page/user/
    - lib/src/page/user/widget/
    - lib/src/page/donor/
    - lib/src/page/intro/
    - lib/src/page/login/
    - lib/src/page/signup/
    - lib/src/page/privacy/
    - lib/src/page/ranking/
    - lib/src/page/sponsor/
    - lib/src/page/sponsor/widget/
    - lib/src/page/unknown/
    - lib/src/page/collaborate/
    - lib/src/model/
    - lib/src/route/
    - lib/src/shared/
    - lib/src/widget/
    - lib/src/repository/
    - lib/src/repository/interface/
    - lib/src/localization/
    - lib/generated/
  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf