name: yodravet
description: Una app de A.E Yo corro por el Dravet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_cupertino_localizations
  # flutter_cupertino_localizations: ^1.0.1
  # https://pub.dev/packages/intl_translation
  # intl_translation: ^0.17.10+1
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.5.0
  # https://pub.dartlang.org/packages/bloc
  bloc: ^3.0.0
  # https://pub.dartlang.org/packages/flutter_bloc
  flutter_bloc: ^3.2.0
  # https://pub.dev/packages/google_fonts
  google_fonts: ^0.3.10
  # https://pub.dev/packages/responsive_builder
  responsive_builder: ^0.3.0
  # https://pub.dev/packages/strava_flutter
  strava_flutter: ^1.2.2+62
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.16.0
  # cloud_firestore: ^1.0.7
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.20.0+1
  # firebase_auth: ^1.1.2
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^4.5.9
  # https://pub.dev/packages/google_sign_in_web
  # google_sign_in_web: ^0.9.2
  # https://pub.dartlang.org/packages/firebase_analytics
  # firebase_analytics: ^7.0.1
  # https://pub.dev/packages/firebase_core
  firebase_core: ^0.7.0
  # firebase_core: ^1.1.0
  # https://pub.dev/packages/rive
  rive: ^0.6.7
  # https://pub.dev/packages/countup
  countup: ^0.1.3
  # https://pub.dev/packages/number_inc_dec
  number_inc_dec: ^0.6.6
  # https://pub.dev/packages/flushbar
  flushbar: ^1.10.4
  # https://pub.dev/packages/flash
  flash: ^2.0.0
  # https://pub.dev/packages/email_validator
  email_validator: ^1.0.6
  # https://pub.dev/packages/sign_in_with_apple
  # https://firebase.flutter.dev/docs/auth/social/
  sign_in_with_apple: ^2.5.4
  crypto: ^2.1.5
  # https://pub.dev/packages/animations∂
  animations: ^1.1.2
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.5
  # https://pub.dev/packages/flutter_launcher_name
  flutter_launcher_name: ^0.0.1

# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

# run flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "Yo Dravet"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/race/spain.riv
    - assets/race/stages/vallhebron.png
    - assets/race/stages/centrofelipe.png
    - assets/race/stages/fmedicinamadrid.png
    - assets/race/stages/rubermadrid.png
    - assets/race/stages/pompeufabra.png
    - assets/race/stages/achucarro.png
    - assets/race/stages/biocruces.png
    - assets/race/stages/biobide.png
    - assets/race/stages/universidadacoruna.png
    - assets/race/stages/universidadnebrija.png
    - assets/race/stages/cabimer.png
    - assets/race/stages/ajsantfeliu.png
    - assets/race/stages/researchers/antoniogilnagelrein.png
    - assets/race/stages/researchers/jonandonidunabeitia.png
    - assets/race/stages/researchers/juancastorivadulla.png
    - assets/race/stages/researchers/juanmanuelencinas.png
    - assets/race/stages/researchers/manuelalvarezdolado.png
    - assets/race/stages/researchers/maximoibogalindo.png
    - assets/race/stages/researchers/paolobonifazi.png
    - assets/race/stages/researchers/victorpuntes.png
    - assets/race/stages/researchers/isabelpino.png
    - assets/race/stages/researchers/jantonnensen.png
    - assets/race/stages/researchers/onintzasagredo.png
    - assets/race/stages/researchers/sandraacosta.png
    - assets/race/stages/researchers/ainhoaalzualde.png
    - assets/race/logoYocorro.png
    - assets/race/logoYocorroSinFondo.png
    - assets/defaultAvatar.png
    - assets/medallas/medalla1.png
    - assets/medallas/medalla2.png
    - assets/medallas/medalla3.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
