name: yodravet
description: Una app de A.E Yo corro por el Dravet.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.0+23

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_cupertino_localizations
  # flutter_cupertino_localizations: ^1.0.1
  # https://pub.dev/packages/intl_translation
  # intl_translation: ^0.17.10+1
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^9.2.0
  # https://pub.dartlang.org/packages/bloc
  bloc: ^8.0.1
  # https://pub.dartlang.org/packages/flutter_bloc
  flutter_bloc: ^8.0.0
  # https://pub.dev/packages/google_fonts
  google_fonts: ^2.1.0
  # https://pub.dev/packages/responsive_builder
  responsive_builder: ^0.4.1
  # https://pub.dev/packages/strava_flutter
  #  strava_flutter: ^1.2.2+62
  strava_flutter:
    git: https://github.com/dreampowder/strava_flutter.git
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^3.1.5
  # cloud_firestore: ^1.0.7
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^3.3.4
  # firebase_auth: ^1.1.2
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^5.2.1
  # https://pub.dev/packages/google_sign_in_web
  # google_sign_in_web: ^0.9.2
  # https://pub.dartlang.org/packages/firebase_analytics
  # firebase_analytics: ^7.0.1
  # https://pub.dev/packages/firebase_core
  firebase_core: ^1.10.6
  # firebase_core: ^1.1.0
  # https://pub.dev/packages/rive
  rive: ^0.8.1
  # https://pub.dev/packages/countup
  #  countup: ^0.1.3
  countup:
    git: https://github.com/alpceylan/flutter-countup.git
  # https://pub.dev/packages/number_inc_dec
  number_inc_dec: ^0.8.0
  # https://pub.dev/packages/flash
  flash: ^2.0.3+1
  # https://pub.dev/packages/email_validator
  email_validator: ^2.0.1
  # https://pub.dev/packages/sign_in_with_apple
  # https://firebase.flutter.dev/docs/auth/social/
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  # https://pub.dev/packages/animations∂
  animations: ^2.0.2
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.17
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.0.5
  # https://pub.dev/packages/assets_audio_player
  assets_audio_player: ^3.0.4+1
  # https://pub.dev/packages/share_plus
  share_plus: ^3.1.0
  # https://pub.dev/packages/cached_network_image_builder
  cached_network_image_builder: ^0.2.0
  # https://pub.dev/packages/firebase_image
  firebase_image: ^1.1.1
  # https://pub.dev/packages/intro_slider
  intro_slider: ^3.0.4
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.13

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.9.2
  # https://pub.dev/packages/flutter_launcher_name
  #  flutter_launcher_name: ^0.0.1
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"

# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

# run flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "Yo Dravet"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/stores/
    - assets/images/race/
    - assets/images/medallas/
    - assets/images/race/stages/
    - assets/images/race/stages/researchers/
    - assets/music/

  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: fonts/AkayaTelivigala-Regular.ttf
