// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrNzN-Sp2dWQxn3ossh_kYXyzaXpAFIX8',
    appId: '1:194761676212:web:d06b3de5f2a42738a5cee1',
    messagingSenderId: '194761676212',
    projectId: 'yo-corro-por-el-dravet',
    authDomain: 'yo-corro-por-el-dravet.firebaseapp.com',
    storageBucket: 'yo-corro-por-el-dravet.appspot.com',
    measurementId: 'G-J0TS44PHVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqWOL0u7d2JjwGfnqF3UI3i2tglY2Iek',
    appId: '1:194761676212:android:9002b159a36b1aa5a5cee1',
    messagingSenderId: '194761676212',
    projectId: 'yo-corro-por-el-dravet',
    storageBucket: 'yo-corro-por-el-dravet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqDnCjHhN_koZumruBn29pgx7x2JsDXQ',
    appId: '1:194761676212:ios:4f0c6d47377890e4a5cee1',
    messagingSenderId: '194761676212',
    projectId: 'yo-corro-por-el-dravet',
    storageBucket: 'yo-corro-por-el-dravet.appspot.com',
    androidClientId: '194761676212-04r5r4buq9n53jkjqaudts6ahdp0c5jr.apps.googleusercontent.com',
    iosClientId: '194761676212-7bbdfk1gs07ua1p2ot7ir7gsp1ftvov7.apps.googleusercontent.com',
    iosBundleId: 'es.yocorroporeldravet.yodravet',
  );
}
